apiVersion: v1
kind: Service
metadata:
  name: student-registration-backend
  namespace: {{ .Values.namespace }}
  annotations:
    # Container-native load balancing: the load balancer talks to Pod IPs directly
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: student-registration-backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: 8080
      protocol: TCP
