{{- if .Values.monitoring.podMonitoring.enabled }}
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: student-registration-backend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: student-registration-backend
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: {{ .Values.monitoring.podMonitoring.interval }}
{{- end }}
